# Generated by Django 4.1.7 on 2023-02-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markdown_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_comment',
            },
        ),
        migrations.CreateModel(
            name='CompanyMarkDown',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companies')),
            ],
            options={
                'db_table': 'company_markdown',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='StudentComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markdown_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_comment',
            },
        ),
        migrations.CreateModel(
            name='StudentMarkDown',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_markdown',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('good_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.skills')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.students')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.universities')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentNice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('markdown_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentmarkdown')),
            ],
            options={
                'db_table': 'student_nice',
            },
        ),
        migrations.AddField(
            model_name='studentmarkdown',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students'),
        ),
        migrations.CreateModel(
            name='StudentFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
            options={
                'db_table': 'student_follow',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.TextField(default='作成中')),
                ('businness_contents', models.TextField(default='作成中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.companies')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyNice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('markdown_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companymarkdown')),
            ],
            options={
                'db_table': 'company_nice',
            },
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companies')),
            ],
            options={
                'db_table': 'company_follow',
            },
        ),
    ]
