name: Run Django Test
on: [ workflow_dispatch ]

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      # pythonのパッケージインストール
      - name: Install Dependencies
        run: |
        python -m pip install --update pip
        pip install -r requirements.txt

      # テスト実行
      - name: Run test
        run: python manage.py test
      