from app.models.users import Users
from app.models.student_profile import StudentProfile
from app.models.company_profile import CompanyProfile
from app.models.skills import Skills
from app.models.skill_middle import SkillMiddle
from app.models.universities import Universities
from app.models.grade import Grade
from app.models.department import Department
from app.models.department_middle import DepartmentMiddle
from app.models.follow import Follow
from app.models.markdown_post import MarkdownPost
from app.models.nice import Nice
from app.models.users import Users
