from app.models.user import User
from app.models.students import Students
from app.models.student_profile import StudentProfile
from app.models.student_comment import StudentComment
from app.models.student_follow import StudentFollow
from app.models.student_markdown import StudentMarkDown
from app.models.student_nice import StudentNice
from app.models.companies import Companies
from app.models.company_comment import CompanyComment
from app.models.company_follow import CompanyFollow
from app.models.company_markdown import CompanyMarkDown
from app.models.company_profile import CompanyProfile
from app.models.company_nice import CompanyNice
from app.models.skills import Skills
from app.models.universities import Universities